name: Python Tests

on:
  push:
    branches:
      - production
  pull_request:
    branches:
      - production

jobs:
  test:
    runs-on: ubuntu-latest

    steps:
    - name: Check the repository code
      uses: actions/checkout@v4

    - name: Set up Python 3.9 environment
      uses: actions/setup-python@v5
      with:
        python-version: '3.12'

    - name: Cache pip dependencies
      uses: actions/cache@v3
      with:
        path: ~/.cache/pip
        key: ${{ runner.os }}-pip-${{ hashFiles('requirements.txt') }}
        restore-keys: |
          ${{ runner.os }}-pip-

    - name: Install dependencies
      run: |
        python -m venv venv
        source venv/bin/activate
        pip install -r requirements.txt

    - name: Set PYTHONPATH
      run: |
        echo "PYTHONPATH=$(pwd)" >> $GITHUB_ENV

    - name: Run the unit tests
      run: |
        source venv/bin/activate
        pytest tests/unit

    - name: Run the integration tests
      run: |
        source venv/bin/activate
        pytest tests/integration